namespace: namespace-name
# dockerconfigjson: base64encodedvalue
# dockerreponame: quay
aws:
  partition: "aws"
  accountId: ""
# irsaRole: "..."
quota:
  requests:
    cpu: "16"
    memory: "32Gi"
  limits:
    cpu: "16"
    memory: "32Gi"
